env: "local"
storage_path: "postgresql://eduplay:sanAnas_918694@eduplay-postgres-postgresql:5432/eduplay-user"
# storage_path: "postgresql://postgres:postgres@localhost:5432/eduplay"
secret_key: "EduplaySecretkey"
# rabbitmq: "amqp://guest:guest@localhost:5672/"
rabbitmq: "amqp://eduplay_user:eduplay0987654321@rabbitmq.eduplay.svc.cluster.local:5672/"
grpc:
  port: 35001
  timeout: 5s
