apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduplay-event
  namespace: eduplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduplay-event
  template:
    metadata:
      labels:
        app: eduplay-event
    spec:
      containers:
        - name: event
          image: notocactus/eduplay-event
          ports:
            - containerPort: 35002
          env:
            - name: CONFIG_PATH
              value: "/config/config.yaml"