apiVersion: v1
kind: Service
metadata:
  name: eduplay-event
  namespace: eduplay
spec:
  selector:
    app: eduplay-event
  ports:
    - name: grpc
      port: 35002
      targetPort: 35002
      protocol: TCP
  type: ClusterIP
