apiVersion: v1
kind: Service
metadata:
  name: eduplay-user
  namespace: eduplay
spec:
  selector:
    app: eduplay-user
  ports:
    - name: grpc
      port: 35001
      targetPort: 35001
      protocol: TCP
  type: ClusterIP
