resources:
  - namespace.yaml
  - eduplay-gateway/deployment.yaml
  - eduplay-gateway/service.yaml
  - eduplay-user/deployment.yaml
  - eduplay-user/service.yaml
  - eduplay-event/deployment.yaml
  - eduplay-event/service.yaml
  - eduplay-notification/deployment.yaml
  - eduplay-notification/service.yaml
  - eduplay-gateway/ingress.yaml
  - eduplay-mail/deployment.yaml
  - eduplay-mail/service.yaml

images:
  - name: notocactus/eduplay-gateway
    newTag: sha-a633324
  - name: notocactus/eduplay-user
    newTag: sha-a633324
  - name: notocactus/eduplay-event
    newTag: sha-a633324
  - name: notocactus/eduplay-notification
    newTag: sha-a633324
  - name: notocactus/eduplay-mail
    newTag: sha-a633324