resources:
  - namespace.yaml
  - eduplay-gateway/deployment.yaml
  - eduplay-gateway/service.yaml
  - eduplay-user/deployment.yaml
  - eduplay-user/service.yaml
  - eduplay-event/deployment.yaml
  - eduplay-event/service.yaml
  - eduplay-notification/deployment.yaml
  - eduplay-notification/service.yaml
  - eduplay-gateway/ingress.yaml

images:
  - name: notocactus/eduplay-gateway
    newTag: sha-b83f5bf
  - name: notocactus/eduplay-user
    newTag: sha-b83f5bf
  - name: notocactus/eduplay-event
    newTag: sha-b83f5bf
  - name: notocactus/eduplay-notification
    newTag: sha-b83f5bf