resources:
  - namespace.yaml
  - eduplay-gateway/deployment.yaml
  - eduplay-gateway/service.yaml
  - eduplay-user/deployment.yaml
  - eduplay-user/service.yaml
  - eduplay-event/deployment.yaml
  - eduplay-event/service.yaml
  - eduplay-gateway/ingress.yaml

images:
  - name: notocactus/eduplay-gateway
    newTag: sha-818c9da
  - name: notocactus/eduplay-user
    newTag: sha-818c9da
  - name: notocactus/eduplay-event
    newTag: sha-818c9da