apiVersion: v1
kind: Service
metadata:
  name: eduplay-gateway
  namespace: eduplay
spec:
  selector:
    app: eduplay-gateway
  ports:
    - name: http
      port: 35000
      targetPort: 35000
  type: ClusterIP
