apiVersion: apps/v1
kind: Deployment
metadata:
  name: eduplay-gateway
  namespace: eduplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eduplay-gateway
  template:
    metadata:
      labels:
        app: eduplay-gateway
    spec:
      containers:
        - name: gateway
          image: notocactus/eduplay-gateway
          ports:
            - containerPort: 35000
          env:
            - name: CONFIG_PATH
              value: "/config/config.yaml"
