// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	userModel "eduplay-gateway/internal/lib/models/user"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// SignUp provides a mock function with given fields: ctx, pd
func (_m *UseCase) SignUp(ctx context.Context, pd *userModel.SignUpRequest) (*userModel.Credentials, error) {
	ret := _m.Called(ctx, pd)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 *userModel.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *userModel.SignUpRequest) (*userModel.Credentials, error)); ok {
		return rf(ctx, pd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *userModel.SignUpRequest) *userModel.Credentials); ok {
		r0 = rf(ctx, pd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userModel.Credentials)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *userModel.SignUpRequest) error); ok {
		r1 = rf(ctx, pd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
