// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	eduplay_event_v1 "eduplay-event/internal/generated"

	mock "github.com/stretchr/testify/mock"

	time "time"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// ClearBlockAnswers provides a mock function with given fields: ctx, userId, blockId
func (_m *Storage) ClearBlockAnswers(ctx context.Context, userId string, blockId string) error {
	ret := _m.Called(ctx, userId, blockId)

	if len(ret) == 0 {
		panic("no return value specified for ClearBlockAnswers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userId, blockId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBlockCondition provides a mock function with given fields: ctx, conditionId
func (_m *Storage) DeleteBlockCondition(ctx context.Context, conditionId string) (string, error) {
	ret := _m.Called(ctx, conditionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlockCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, conditionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, conditionId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, conditionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: ctx, eventId
func (_m *Storage) DeleteEvent(ctx context.Context, eventId string) (string, error) {
	ret := _m.Called(ctx, eventId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, eventId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEventBlock provides a mock function with given fields: ctx, blockId
func (_m *Storage) DeleteEventBlock(ctx context.Context, blockId string) (string, error) {
	ret := _m.Called(ctx, blockId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEventBlock")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, blockId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, blockId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blockId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTaskById provides a mock function with given fields: ctx, taskId
func (_m *Storage) DeleteTaskById(ctx context.Context, taskId string) (string, error) {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, taskId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, taskId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EndMe provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) EndMe(ctx context.Context, userId string, eventId string) (string, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for EndMe")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTags provides a mock function with given fields: ctx
func (_m *Storage) GetAllTags(ctx context.Context) (*eduplay_event_v1.Tags, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTags")
	}

	var r0 *eduplay_event_v1.Tags
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*eduplay_event_v1.Tags, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *eduplay_event_v1.Tags); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Tags)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockConditionsFull provides a mock function with given fields: ctx, id
func (_m *Storage) GetBlockConditionsFull(ctx context.Context, id string) (*eduplay_event_v1.BlockInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockConditionsFull")
	}

	var r0 *eduplay_event_v1.BlockInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.BlockInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.BlockInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.BlockInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockInfo provides a mock function with given fields: ctx, id
func (_m *Storage) GetBlockInfo(ctx context.Context, id string) (*eduplay_event_v1.PostEventBlockIn, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockInfo")
	}

	var r0 *eduplay_event_v1.PostEventBlockIn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.PostEventBlockIn, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.PostEventBlockIn); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PostEventBlockIn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockMaxPoints provides a mock function with given fields: ctx, blockId
func (_m *Storage) GetBlockMaxPoints(ctx context.Context, blockId string) (int64, error) {
	ret := _m.Called(ctx, blockId)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockMaxPoints")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, blockId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, blockId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blockId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockProgress provides a mock function with given fields: ctx, in
func (_m *Storage) GetBlockProgress(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.BlockProgress, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockProgress")
	}

	var r0 *eduplay_event_v1.BlockProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.BlockProgress, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.BlockProgress); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.BlockProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockTasks provides a mock function with given fields: ctx, blockId
func (_m *Storage) GetBlockTasks(ctx context.Context, blockId string) (*eduplay_event_v1.Tasks, error) {
	ret := _m.Called(ctx, blockId)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockTasks")
	}

	var r0 *eduplay_event_v1.Tasks
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.Tasks, error)); ok {
		return rf(ctx, blockId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.Tasks); ok {
		r0 = rf(ctx, blockId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Tasks)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blockId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCollaborators provides a mock function with given fields: ctx, eventId
func (_m *Storage) GetCollaborators(ctx context.Context, eventId string) (*eduplay_event_v1.GetCollaboratorsOut, error) {
	ret := _m.Called(ctx, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetCollaborators")
	}

	var r0 *eduplay_event_v1.GetCollaboratorsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.GetCollaboratorsOut, error)); ok {
		return rf(ctx, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.GetCollaboratorsOut); ok {
		r0 = rf(ctx, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetCollaboratorsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvent provides a mock function with given fields: ctx, id
func (_m *Storage) GetEvent(ctx context.Context, id string) (*eduplay_event_v1.PostEventIn, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *eduplay_event_v1.PostEventIn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.PostEventIn, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.PostEventIn); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PostEventIn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventBlocks provides a mock function with given fields: ctx, eventId
func (_m *Storage) GetEventBlocks(ctx context.Context, eventId string) (*eduplay_event_v1.GetEventBlocksOut, error) {
	ret := _m.Called(ctx, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetEventBlocks")
	}

	var r0 *eduplay_event_v1.GetEventBlocksOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.GetEventBlocksOut, error)); ok {
		return rf(ctx, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.GetEventBlocksOut); ok {
		r0 = rf(ctx, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetEventBlocksOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventByJoinCode provides a mock function with given fields: ctx, joinCode
func (_m *Storage) GetEventByJoinCode(ctx context.Context, joinCode string) (string, error) {
	ret := _m.Called(ctx, joinCode)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByJoinCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, joinCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, joinCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, joinCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventProgress provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) GetEventProgress(ctx context.Context, userId string, eventId string) (string, string, bool, time.Time, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetEventProgress")
	}

	var r0 string
	var r1 string
	var r2 bool
	var r3 time.Time
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, bool, time.Time, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) bool); ok {
		r2 = rf(ctx, userId, eventId)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) time.Time); ok {
		r3 = rf(ctx, userId, eventId)
	} else {
		r3 = ret.Get(3).(time.Time)
	}

	if rf, ok := ret.Get(4).(func(context.Context, string, string) error); ok {
		r4 = rf(ctx, userId, eventId)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// GetEventUserRating provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) GetEventUserRating(ctx context.Context, userId string, eventId string) (int64, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetEventUserRating")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventUsers provides a mock function with given fields: ctx, eventId
func (_m *Storage) GetEventUsers(ctx context.Context, eventId string) (*eduplay_event_v1.GetCollaboratorsOut, error) {
	ret := _m.Called(ctx, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetEventUsers")
	}

	var r0 *eduplay_event_v1.GetCollaboratorsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.GetCollaboratorsOut, error)); ok {
		return rf(ctx, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.GetCollaboratorsOut); ok {
		r0 = rf(ctx, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetCollaboratorsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupUsers provides a mock function with given fields: ctx, groupId
func (_m *Storage) GetGroupUsers(ctx context.Context, groupId string) (*eduplay_event_v1.GetGroupUsersOut, error) {
	ret := _m.Called(ctx, groupId)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupUsers")
	}

	var r0 *eduplay_event_v1.GetGroupUsersOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.GetGroupUsersOut, error)); ok {
		return rf(ctx, groupId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.GetGroupUsersOut); ok {
		r0 = rf(ctx, groupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetGroupUsersOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx, eventId
func (_m *Storage) GetGroups(ctx context.Context, eventId string) (*eduplay_event_v1.GetGroupsOut, error) {
	ret := _m.Called(ctx, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 *eduplay_event_v1.GetGroupsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.GetGroupsOut, error)); ok {
		return rf(ctx, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.GetGroupsOut); ok {
		r0 = rf(ctx, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetGroupsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: ctx, in
func (_m *Storage) GetHistory(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJoinCode provides a mock function with given fields: ctx, eventId
func (_m *Storage) GetJoinCode(ctx context.Context, eventId string) (*eduplay_event_v1.JoinCode, error) {
	ret := _m.Called(ctx, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetJoinCode")
	}

	var r0 *eduplay_event_v1.JoinCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.JoinCode, error)); ok {
		return rf(ctx, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.JoinCode); ok {
		r0 = rf(ctx, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.JoinCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNextStage provides a mock function with given fields: ctx, stage
func (_m *Storage) GetNextStage(ctx context.Context, stage *eduplay_event_v1.UserEventIds) (string, string, string, bool, *timestamppb.Timestamp, error) {
	ret := _m.Called(ctx, stage)

	if len(ret) == 0 {
		panic("no return value specified for GetNextStage")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 bool
	var r4 *timestamppb.Timestamp
	var r5 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (string, string, string, bool, *timestamppb.Timestamp, error)); ok {
		return rf(ctx, stage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) string); ok {
		r0 = rf(ctx, stage)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) string); ok {
		r1 = rf(ctx, stage)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *eduplay_event_v1.UserEventIds) string); ok {
		r2 = rf(ctx, stage)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, *eduplay_event_v1.UserEventIds) bool); ok {
		r3 = rf(ctx, stage)
	} else {
		r3 = ret.Get(3).(bool)
	}

	if rf, ok := ret.Get(4).(func(context.Context, *eduplay_event_v1.UserEventIds) *timestamppb.Timestamp); ok {
		r4 = rf(ctx, stage)
	} else {
		if ret.Get(4) != nil {
			r4 = ret.Get(4).(*timestamppb.Timestamp)
		}
	}

	if rf, ok := ret.Get(5).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r5 = rf(ctx, stage)
	} else {
		r5 = ret.Error(5)
	}

	return r0, r1, r2, r3, r4, r5
}

// GetOwnedEvents provides a mock function with given fields: ctx, in
func (_m *Storage) GetOwnedEvents(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnedEvents")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicEvent provides a mock function with given fields: ctx, ids
func (_m *Storage) GetPublicEvent(ctx context.Context, ids *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.GetPublicEvent, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicEvent")
	}

	var r0 *eduplay_event_v1.GetPublicEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.GetPublicEvent, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.GetPublicEvent); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicEvents provides a mock function with given fields: ctx, in
func (_m *Storage) GetPublicEvents(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicEvents")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRole provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) GetRole(ctx context.Context, userId string, eventId string) (int64, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskAnswer provides a mock function with given fields: ctx, taskId, userId
func (_m *Storage) GetTaskAnswer(ctx context.Context, taskId string, userId string) (*eduplay_event_v1.Answer, error) {
	ret := _m.Called(ctx, taskId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskAnswer")
	}

	var r0 *eduplay_event_v1.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*eduplay_event_v1.Answer, error)); ok {
		return rf(ctx, taskId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *eduplay_event_v1.Answer); ok {
		r0 = rf(ctx, taskId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, taskId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskById provides a mock function with given fields: ctx, taskId
func (_m *Storage) GetTaskById(ctx context.Context, taskId string) (*eduplay_event_v1.Task, error) {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskById")
	}

	var r0 *eduplay_event_v1.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_event_v1.Task, error)); ok {
		return rf(ctx, taskId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_event_v1.Task); ok {
		r0 = rf(ctx, taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAnswers provides a mock function with given fields: ctx, in
func (_m *Storage) GetUserAnswers(ctx context.Context, in *eduplay_event_v1.UserEventIds) (int64, int64, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAnswers")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (int64, int64, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) int64); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) int64); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r2 = rf(ctx, in)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserBlockPointsSum provides a mock function with given fields: ctx, userId, blockId
func (_m *Storage) GetUserBlockPointsSum(ctx context.Context, userId string, blockId string) (int64, error) {
	ret := _m.Called(ctx, userId, blockId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBlockPointsSum")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, userId, blockId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, userId, blockId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, blockId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBlockTasksShort provides a mock function with given fields: ctx, blockId, userId
func (_m *Storage) GetUserBlockTasksShort(ctx context.Context, blockId string, userId string) ([]*eduplay_event_v1.NextStageTaskShort, error) {
	ret := _m.Called(ctx, blockId, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBlockTasksShort")
	}

	var r0 []*eduplay_event_v1.NextStageTaskShort
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*eduplay_event_v1.NextStageTaskShort, error)); ok {
		return rf(ctx, blockId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*eduplay_event_v1.NextStageTaskShort); ok {
		r0 = rf(ctx, blockId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*eduplay_event_v1.NextStageTaskShort)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, blockId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserFavorites provides a mock function with given fields: ctx, in
func (_m *Storage) GetUserFavorites(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFavorites")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserGroup provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) GetUserGroup(ctx context.Context, userId string, eventId string) (*eduplay_event_v1.GetUserGroupOut, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroup")
	}

	var r0 *eduplay_event_v1.GetUserGroupOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*eduplay_event_v1.GetUserGroupOut, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *eduplay_event_v1.GetUserGroupOut); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetUserGroupOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserStats provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) GetUserStats(ctx context.Context, userId string, eventId string) (*eduplay_event_v1.User, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStats")
	}

	var r0 *eduplay_event_v1.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*eduplay_event_v1.User, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *eduplay_event_v1.User); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserStatus provides a mock function with given fields: ctx, userId, eventId
func (_m *Storage) GetUserStatus(ctx context.Context, userId string, eventId string) (*eduplay_event_v1.UserStatus, error) {
	ret := _m.Called(ctx, userId, eventId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatus")
	}

	var r0 *eduplay_event_v1.UserStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*eduplay_event_v1.UserStatus, error)); ok {
		return rf(ctx, userId, eventId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *eduplay_event_v1.UserStatus); ok {
		r0 = rf(ctx, userId, eventId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.UserStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, eventId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertJoinCode provides a mock function with given fields: ctx, eventId, joinCode
func (_m *Storage) InsertJoinCode(ctx context.Context, eventId string, joinCode string) (*time.Time, error) {
	ret := _m.Called(ctx, eventId, joinCode)

	if len(ret) == 0 {
		panic("no return value specified for InsertJoinCode")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*time.Time, error)); ok {
		return rf(ctx, eventId, joinCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *time.Time); ok {
		r0 = rf(ctx, eventId, joinCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, eventId, joinCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostAnswer provides a mock function with given fields: ctx, answer
func (_m *Storage) PostAnswer(ctx context.Context, answer *eduplay_event_v1.Answer) (string, error) {
	ret := _m.Called(ctx, answer)

	if len(ret) == 0 {
		panic("no return value specified for PostAnswer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Answer) (string, error)); ok {
		return rf(ctx, answer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Answer) string); ok {
		r0 = rf(ctx, answer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Answer) error); ok {
		r1 = rf(ctx, answer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostBlockCondition provides a mock function with given fields: ctx, in
func (_m *Storage) PostBlockCondition(ctx context.Context, in *eduplay_event_v1.Condition) (*eduplay_event_v1.PostConditionOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostBlockCondition")
	}

	var r0 *eduplay_event_v1.PostConditionOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) (*eduplay_event_v1.PostConditionOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) *eduplay_event_v1.PostConditionOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PostConditionOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Condition) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostComplaint provides a mock function with given fields: ctx, in
func (_m *Storage) PostComplaint(ctx context.Context, in *eduplay_event_v1.PostComplaintIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostComplaint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostComplaintIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostComplaintIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostComplaintIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostEvent provides a mock function with given fields: ctx, in
func (_m *Storage) PostEvent(ctx context.Context, in *eduplay_event_v1.PostEventIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostEvent")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostEventIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostEventBlock provides a mock function with given fields: ctx, in
func (_m *Storage) PostEventBlock(ctx context.Context, in *eduplay_event_v1.PostEventBlockIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostEventBlock")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostParticipant provides a mock function with given fields: ctx, userId, eventId, groupId
func (_m *Storage) PostParticipant(ctx context.Context, userId string, eventId string, groupId string) (string, error) {
	ret := _m.Called(ctx, userId, eventId, groupId)

	if len(ret) == 0 {
		panic("no return value specified for PostParticipant")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, userId, eventId, groupId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userId, eventId, groupId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userId, eventId, groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRate provides a mock function with given fields: ctx, in
func (_m *Storage) PostRate(ctx context.Context, in *eduplay_event_v1.Rate) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostRate")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Rate) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Rate) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Rate) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostTask provides a mock function with given fields: ctx, in
func (_m *Storage) PostTask(ctx context.Context, in *eduplay_event_v1.Task) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Task) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutBlockCondition provides a mock function with given fields: ctx, in
func (_m *Storage) PutBlockCondition(ctx context.Context, in *eduplay_event_v1.Condition) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutBlockCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Condition) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutBlockList provides a mock function with given fields: ctx, in
func (_m *Storage) PutBlockList(ctx context.Context, in *eduplay_event_v1.PutListIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutBlockList")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutListIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEvent provides a mock function with given fields: ctx, in
func (_m *Storage) PutEvent(ctx context.Context, in *eduplay_event_v1.PutEventIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutEvent")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutEventIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutEventIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutEventIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEventBlock provides a mock function with given fields: ctx, in
func (_m *Storage) PutEventBlock(ctx context.Context, in *eduplay_event_v1.PostEventBlockIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutEventBlock")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEventBlockName provides a mock function with given fields: ctx, in
func (_m *Storage) PutEventBlockName(ctx context.Context, in *eduplay_event_v1.Tag) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutEventBlockName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Tag) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Tag) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Tag) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutFavorite provides a mock function with given fields: ctx, in
func (_m *Storage) PutFavorite(ctx context.Context, in *eduplay_event_v1.PutFavoriteIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutFavorite")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutFavoriteIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutFavoriteIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutFavoriteIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutGroupsInCondition provides a mock function with given fields: ctx, in
func (_m *Storage) PutGroupsInCondition(ctx context.Context, in *eduplay_event_v1.PutListIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutGroupsInCondition")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutListIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutNextStage provides a mock function with given fields: ctx, stage
func (_m *Storage) PutNextStage(ctx context.Context, stage *eduplay_event_v1.EventBlockTaskUserIds) (string, error) {
	ret := _m.Called(ctx, stage)

	if len(ret) == 0 {
		panic("no return value specified for PutNextStage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBlockTaskUserIds) (string, error)); ok {
		return rf(ctx, stage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBlockTaskUserIds) string); ok {
		r0 = rf(ctx, stage)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBlockTaskUserIds) error); ok {
		r1 = rf(ctx, stage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTask provides a mock function with given fields: ctx, in
func (_m *Storage) PutTask(ctx context.Context, in *eduplay_event_v1.Task) (*eduplay_event_v1.PutTaskOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutTask")
	}

	var r0 *eduplay_event_v1.PutTaskOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) (*eduplay_event_v1.PutTaskOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) *eduplay_event_v1.PutTaskOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PutTaskOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Task) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTaskList provides a mock function with given fields: ctx, in
func (_m *Storage) PutTaskList(ctx context.Context, in *eduplay_event_v1.PutListIn) (string, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutTaskList")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) (string, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) string); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutListIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTimestamp provides a mock function with given fields: ctx, userId, eventId, timestamp
func (_m *Storage) PutTimestamp(ctx context.Context, userId string, eventId string, timestamp *timestamppb.Timestamp) (string, error) {
	ret := _m.Called(ctx, userId, eventId, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for PutTimestamp")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *timestamppb.Timestamp) (string, error)); ok {
		return rf(ctx, userId, eventId, timestamp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *timestamppb.Timestamp) string); ok {
		r0 = rf(ctx, userId, eventId, timestamp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *timestamppb.Timestamp) error); ok {
		r1 = rf(ctx, userId, eventId, timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveFile provides a mock function with given fields: ctx, fileName, fileKey, fileUUID
func (_m *Storage) SaveFile(ctx context.Context, fileName string, fileKey string, fileUUID string) (string, error) {
	ret := _m.Called(ctx, fileName, fileKey, fileUUID)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, fileName, fileKey, fileUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, fileName, fileKey, fileUUID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, fileName, fileKey, fileUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEventCollaborators provides a mock function with given fields: ctx, eventId, collaboratorIds
func (_m *Storage) UpdateEventCollaborators(ctx context.Context, eventId string, collaboratorIds []string) error {
	ret := _m.Called(ctx, eventId, collaboratorIds)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEventCollaborators")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, eventId, collaboratorIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEventGroups provides a mock function with given fields: ctx, eventId, groups
func (_m *Storage) UpdateEventGroups(ctx context.Context, eventId string, groups []*eduplay_event_v1.Group) error {
	ret := _m.Called(ctx, eventId, groups)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEventGroups")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*eduplay_event_v1.Group) error); ok {
		r0 = rf(ctx, eventId, groups)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newStorage creates a new instance of storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
