env: "local"
server: 
  address: "0.0.0.0:35000"
  timeout: 5s
  idle_timeout: 5s
clients: 
  users: 
    address: "eduplay-user:35001"
    timeout: 5s
    retries: 5
  events:
    address: "eduplay-event:35002"
    timeout: 5s
    retries: 5
