// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	eduplay_event_v1 "eduplay-gateway/internal/generated/clients/event"

	mock "github.com/stretchr/testify/mock"
)

// EventClient is an autogenerated mock type for the EventClient type
type EventClient struct {
	mock.Mock
}

// DeleteBlockById provides a mock function with given fields: ctx, in
func (_m *EventClient) DeleteBlockById(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlockById")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBlockCondition provides a mock function with given fields: ctx, in
func (_m *EventClient) DeleteBlockCondition(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlockCondition")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEventById provides a mock function with given fields: ctx, in
func (_m *EventClient) DeleteEventById(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEventById")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTaskById provides a mock function with given fields: ctx, in
func (_m *EventClient) DeleteTaskById(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTaskById")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllTags provides a mock function with given fields: ctx
func (_m *EventClient) GetAllTags(ctx context.Context) (*eduplay_event_v1.Tags, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTags")
	}

	var r0 *eduplay_event_v1.Tags
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*eduplay_event_v1.Tags, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *eduplay_event_v1.Tags); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Tags)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockConditions provides a mock function with given fields: ctx, in
func (_m *EventClient) GetBlockConditions(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.BlockInfo, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockConditions")
	}

	var r0 *eduplay_event_v1.BlockInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.BlockInfo, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.BlockInfo); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.BlockInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockInfo provides a mock function with given fields: ctx, in
func (_m *EventClient) GetBlockInfo(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.PostEventBlockIn, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockInfo")
	}

	var r0 *eduplay_event_v1.PostEventBlockIn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.PostEventBlockIn, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.PostEventBlockIn); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PostEventBlockIn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockProgress provides a mock function with given fields: ctx, in
func (_m *EventClient) GetBlockProgress(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.BlockProgress, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockProgress")
	}

	var r0 *eduplay_event_v1.BlockProgress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.BlockProgress, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.BlockProgress); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.BlockProgress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockTasks provides a mock function with given fields: ctx, in
func (_m *EventClient) GetBlockTasks(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.Tasks, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockTasks")
	}

	var r0 *eduplay_event_v1.Tasks
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.Tasks, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.Tasks); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Tasks)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCollaborators provides a mock function with given fields: ctx, in
func (_m *EventClient) GetCollaborators(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.GetCollaboratorsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetCollaborators")
	}

	var r0 *eduplay_event_v1.GetCollaboratorsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.GetCollaboratorsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.GetCollaboratorsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetCollaboratorsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvent provides a mock function with given fields: ctx, in
func (_m *EventClient) GetEvent(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.PostEventIn, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetEvent")
	}

	var r0 *eduplay_event_v1.PostEventIn
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.PostEventIn, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.PostEventIn); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PostEventIn)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventBlocks provides a mock function with given fields: ctx, in
func (_m *EventClient) GetEventBlocks(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.GetEventBlocksOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetEventBlocks")
	}

	var r0 *eduplay_event_v1.GetEventBlocksOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.GetEventBlocksOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.GetEventBlocksOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetEventBlocksOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventByJoinCode provides a mock function with given fields: ctx, in
func (_m *EventClient) GetEventByJoinCode(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.Id, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByJoinCode")
	}

	var r0 *eduplay_event_v1.Id
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.Id, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.Id); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Id)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventForUser provides a mock function with given fields: ctx, in
func (_m *EventClient) GetEventForUser(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.GetPublicEvent, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetEventForUser")
	}

	var r0 *eduplay_event_v1.GetPublicEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.GetPublicEvent, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.GetPublicEvent); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventUserRating provides a mock function with given fields: ctx, in
func (_m *EventClient) GetEventUserRating(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetEventUserRating")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventUsers provides a mock function with given fields: ctx, in
func (_m *EventClient) GetEventUsers(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.GetCollaboratorsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetEventUsers")
	}

	var r0 *eduplay_event_v1.GetCollaboratorsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.GetCollaboratorsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.GetCollaboratorsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetCollaboratorsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupUsers provides a mock function with given fields: ctx, in
func (_m *EventClient) GetGroupUsers(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.GetGroupUsersOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupUsers")
	}

	var r0 *eduplay_event_v1.GetGroupUsersOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.GetGroupUsersOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.GetGroupUsersOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetGroupUsersOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroups provides a mock function with given fields: ctx, in
func (_m *EventClient) GetGroups(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.GetGroupsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 *eduplay_event_v1.GetGroupsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.GetGroupsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.GetGroupsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetGroupsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: ctx, in
func (_m *EventClient) GetHistory(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJoinCode provides a mock function with given fields: ctx, in
func (_m *EventClient) GetJoinCode(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.JoinCode, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetJoinCode")
	}

	var r0 *eduplay_event_v1.JoinCode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.JoinCode, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.JoinCode); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.JoinCode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNextStage provides a mock function with given fields: ctx, in
func (_m *EventClient) GetNextStage(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.NextStageInfo, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetNextStage")
	}

	var r0 *eduplay_event_v1.NextStageInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.NextStageInfo, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.NextStageInfo); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.NextStageInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOwnedEvents provides a mock function with given fields: ctx, in
func (_m *EventClient) GetOwnedEvents(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetOwnedEvents")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublicEvents provides a mock function with given fields: ctx, in
func (_m *EventClient) GetPublicEvents(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicEvents")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRole provides a mock function with given fields: ctx, in
func (_m *EventClient) GetRole(ctx context.Context, in *eduplay_event_v1.GetRoleIn) (*eduplay_event_v1.GetRoleOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 *eduplay_event_v1.GetRoleOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.GetRoleIn) (*eduplay_event_v1.GetRoleOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.GetRoleIn) *eduplay_event_v1.GetRoleOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetRoleOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.GetRoleIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskById provides a mock function with given fields: ctx, in
func (_m *EventClient) GetTaskById(ctx context.Context, in *eduplay_event_v1.Id) (*eduplay_event_v1.Task, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskById")
	}

	var r0 *eduplay_event_v1.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) (*eduplay_event_v1.Task, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Id) *eduplay_event_v1.Task); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Id) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAnswers provides a mock function with given fields: ctx, in
func (_m *EventClient) GetUserAnswers(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.UserAnswers, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAnswers")
	}

	var r0 *eduplay_event_v1.UserAnswers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.UserAnswers, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.UserAnswers); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.UserAnswers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserFavorites provides a mock function with given fields: ctx, in
func (_m *EventClient) GetUserFavorites(ctx context.Context, in *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserFavorites")
	}

	var r0 *eduplay_event_v1.GetPublicEventsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) (*eduplay_event_v1.GetPublicEventsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBaseFilters) *eduplay_event_v1.GetPublicEventsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetPublicEventsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBaseFilters) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserGroup provides a mock function with given fields: ctx, in
func (_m *EventClient) GetUserGroup(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.GetUserGroupOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroup")
	}

	var r0 *eduplay_event_v1.GetUserGroupOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.GetUserGroupOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.GetUserGroupOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetUserGroupOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserStats provides a mock function with given fields: ctx, in
func (_m *EventClient) GetUserStats(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStats")
	}

	var r0 *eduplay_event_v1.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserStatus provides a mock function with given fields: ctx, in
func (_m *EventClient) GetUserStatus(ctx context.Context, in *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.UserStatus, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetUserStatus")
	}

	var r0 *eduplay_event_v1.UserStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) (*eduplay_event_v1.UserStatus, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.UserEventIds) *eduplay_event_v1.UserStatus); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.UserStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.UserEventIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostAnswer provides a mock function with given fields: ctx, in
func (_m *EventClient) PostAnswer(ctx context.Context, in *eduplay_event_v1.Answer) (*eduplay_event_v1.Answer, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostAnswer")
	}

	var r0 *eduplay_event_v1.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Answer) (*eduplay_event_v1.Answer, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Answer) *eduplay_event_v1.Answer); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Answer) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostAnswerBatch provides a mock function with given fields: ctx, in
func (_m *EventClient) PostAnswerBatch(ctx context.Context, in *eduplay_event_v1.AnswerBatch) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostAnswerBatch")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.AnswerBatch) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.AnswerBatch) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.AnswerBatch) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostBlockCondition provides a mock function with given fields: ctx, in
func (_m *EventClient) PostBlockCondition(ctx context.Context, in *eduplay_event_v1.Condition) (*eduplay_event_v1.PostConditionOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostBlockCondition")
	}

	var r0 *eduplay_event_v1.PostConditionOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) (*eduplay_event_v1.PostConditionOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) *eduplay_event_v1.PostConditionOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PostConditionOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Condition) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostComplaint provides a mock function with given fields: ctx, in
func (_m *EventClient) PostComplaint(ctx context.Context, in *eduplay_event_v1.PostComplaintIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostComplaint")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostComplaintIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostComplaintIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostComplaintIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostEvent provides a mock function with given fields: ctx, in
func (_m *EventClient) PostEvent(ctx context.Context, in *eduplay_event_v1.PostEventIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostEvent")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostEventIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostEventBlock provides a mock function with given fields: ctx, in
func (_m *EventClient) PostEventBlock(ctx context.Context, in *eduplay_event_v1.PostEventBlockIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostEventBlock")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostParticipant provides a mock function with given fields: ctx, in
func (_m *EventClient) PostParticipant(ctx context.Context, in *eduplay_event_v1.PostParticipantIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostParticipant")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostParticipantIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostParticipantIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostParticipantIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRate provides a mock function with given fields: ctx, in
func (_m *EventClient) PostRate(ctx context.Context, in *eduplay_event_v1.Rate) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostRate")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Rate) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Rate) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Rate) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostTask provides a mock function with given fields: ctx, in
func (_m *EventClient) PostTask(ctx context.Context, in *eduplay_event_v1.Task) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PostTask")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Task) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutBlockCondition provides a mock function with given fields: ctx, in
func (_m *EventClient) PutBlockCondition(ctx context.Context, in *eduplay_event_v1.Condition) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutBlockCondition")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Condition) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Condition) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutBlockList provides a mock function with given fields: ctx, in
func (_m *EventClient) PutBlockList(ctx context.Context, in *eduplay_event_v1.PutListIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutBlockList")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutListIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEvent provides a mock function with given fields: ctx, in
func (_m *EventClient) PutEvent(ctx context.Context, in *eduplay_event_v1.PutEventIn) (*eduplay_event_v1.GetGroupsOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutEvent")
	}

	var r0 *eduplay_event_v1.GetGroupsOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutEventIn) (*eduplay_event_v1.GetGroupsOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutEventIn) *eduplay_event_v1.GetGroupsOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.GetGroupsOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutEventIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEventBlock provides a mock function with given fields: ctx, in
func (_m *EventClient) PutEventBlock(ctx context.Context, in *eduplay_event_v1.PostEventBlockIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutEventBlock")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PostEventBlockIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutEventBlockName provides a mock function with given fields: ctx, in
func (_m *EventClient) PutEventBlockName(ctx context.Context, in *eduplay_event_v1.Tag) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutEventBlockName")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Tag) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Tag) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Tag) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutFavorite provides a mock function with given fields: ctx, in
func (_m *EventClient) PutFavorite(ctx context.Context, in *eduplay_event_v1.PutFavoriteIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutFavorite")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutFavoriteIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutFavoriteIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutFavoriteIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutGroups provides a mock function with given fields: ctx, in
func (_m *EventClient) PutGroups(ctx context.Context, in *eduplay_event_v1.PutListIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutGroups")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutListIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutNextStage provides a mock function with given fields: ctx, in
func (_m *EventClient) PutNextStage(ctx context.Context, in *eduplay_event_v1.EventBlockTaskUserIds) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutNextStage")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBlockTaskUserIds) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.EventBlockTaskUserIds) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.EventBlockTaskUserIds) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTask provides a mock function with given fields: ctx, in
func (_m *EventClient) PutTask(ctx context.Context, in *eduplay_event_v1.Task) (*eduplay_event_v1.PutTaskOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutTask")
	}

	var r0 *eduplay_event_v1.PutTaskOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) (*eduplay_event_v1.PutTaskOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.Task) *eduplay_event_v1.PutTaskOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.PutTaskOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.Task) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTaskList provides a mock function with given fields: ctx, in
func (_m *EventClient) PutTaskList(ctx context.Context, in *eduplay_event_v1.PutListIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutTaskList")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutListIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutListIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutTimestamp provides a mock function with given fields: ctx, in
func (_m *EventClient) PutTimestamp(ctx context.Context, in *eduplay_event_v1.PutTimestampIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for PutTimestamp")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutTimestampIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.PutTimestampIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.PutTimestampIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveFile provides a mock function with given fields: ctx, in
func (_m *EventClient) SaveFile(ctx context.Context, in *eduplay_event_v1.SaveFileIn) (*eduplay_event_v1.MessageOut, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 *eduplay_event_v1.MessageOut
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.SaveFileIn) (*eduplay_event_v1.MessageOut, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eduplay_event_v1.SaveFileIn) *eduplay_event_v1.MessageOut); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_event_v1.MessageOut)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eduplay_event_v1.SaveFileIn) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventClient creates a new instance of EventClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventClient {
	mock := &EventClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
