// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	eduplay_user_v1 "eduplay-gateway/internal/generated/clients/user"

	mock "github.com/stretchr/testify/mock"
)

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

// GetProfile provides a mock function with given fields: ctx, userId
func (_m *UserClient) GetProfile(ctx context.Context, userId string) (*eduplay_user_v1.Profile, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *eduplay_user_v1.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_user_v1.Profile, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_user_v1.Profile); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_user_v1.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileByLogin provides a mock function with given fields: ctx, login
func (_m *UserClient) GetProfileByLogin(ctx context.Context, login string) (*eduplay_user_v1.Profile, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByLogin")
	}

	var r0 *eduplay_user_v1.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*eduplay_user_v1.Profile, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *eduplay_user_v1.Profile); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eduplay_user_v1.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
