# name: Build the docker image

# on: 
#   push: 
#     branches: 
#       - main

# env: 
#   WORK_DIR: /home/cactus/eduplay

# jobs: 

#   build:
#     runs-on: ubuntu-latest

#     env: 
#       IMG_REG: emp-manage
#       REPO: emp-manage-backend
#       REPO_PATH: /home/cactus/eduplay/emp-manage-backend
#     steps: 
#       - name: check out the code
#         uses: actions/checkout@v4
#       - name: Get short SHA
#         uses: benjlevesque/short-sha@v3.0 
#         id: short-shaa
#         with: 
#           length: 5
#       - run: echo $SHA
#         env:
#           SHA: ${{ env.SHA }}
      
#       - name: Set SHA Output to use in release
#         run: |
#           cd ${{ env.WORK_DIR }}
#           touch env_file.txt
#           chmod 766 env_file.txt
#           echo "${{ env.SHA }}" > env_file.txt
      
#       - name: build docker image
#         run: | 
#           cd ${{ env.REPO_PATH }}
#           docker build -t yashashp/${{ env.IMG_REG }}:${{ env.SHA }} .

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASS }}
      
#       - name: Push Docker image
#         run: |
#           docker push yashashp/${{ env.IMG_REG }}:${{ env.SHA }}


# release: 
#   runs-on: ubuntu-latest
#   needs: build
#   steps: 
#     - name: Get env 
#       id: short-sha-value
#       run: |
#         cd ${{ env.WORK_DIR }}
#         sha=$(cat env_file.txt)
#         echo "tag=$sha" >> $GITHUB_ENV
#     - name: Create release
#       id: create_release
#       uses: actions/create-release@v1
#       env: 
#         GITHUB_TOKEN: ${{ secrets.github_token }}
#       with: 
#         tag_name: ${{ env.tag }}
#         release_name: Release ${{ env.tag }}
#         body: New release for ${{ github.sha }}. Release notes can be found in the docs.
#         draft: false
#         prerelease: false

# clean: 
#   runs-on: ubuntu-latest
#   needs: release
#   env: 
#     REPO: emp-manage-backend
#   steps: 
#     - name: clean working directory
#       run: |
#         cd ${{ env.WORK_DIR }}
#         rm env_file.txt
#         rm -rf ${{ env.REPO }}
#         rm -rf _PipelineMapping _temp _tool