name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ "eduplay-gateway", "eduplay-user", "eduplay-event", "eduplay-notification" ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      # - name: Cache golangci-lint
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/golangci-lint
      #     key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.mod') }}

      # - name: Install golangci-lint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: v1.64.8

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8

      - name: Run linter
        working-directory: ${{ matrix.service }}
        # run: golangci-lint run --config=/dev/null --timeout=5m
        run: golangci-lint run --timeout=5m

      - name: Run tests
        working-directory: ${{ matrix.service }}
        run: go test ./... -v

      - name: Build service
        working-directory: ${{ matrix.service }}
        run: go build ./...
